### ISSUE TITLE
Error when don't have permission to publish

### ISSUE THREAD

**Issue by billgeo** [SPlanzer/nzgoal_audit_script#1]
Hey @SPlanzer, I get this error when going down the path of:

1. Copyrighted work
2. Don't have permission to publish
3. Hit ok (weirdly there's two OK buttons?)

See latest google sheet (has two ok responses (no question in the header though?)

```
SCRIPT FAILED WHEN MATCHING TSV HEADER TEXT WITH CODE FOR 
                        FOR CATEGORISATION. 
 Has the forms outcomes wording changed?
```

**Comment by SPlanzer** [comment]
This has been resolved. 

I have run through a successful round of testing without issue. 

Time for a real user have a go and provide feedback on the process and documentation
